module.exports = {
    JOIN_ROOM: "JOIN_ROOM",
    JOINED_TO_ROOM: "JOINED_TO_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    MESSAGE_RECIEVE: "MESSAGE_RECIEVE",
    SEND_MESSAGE: "SEND_MESSAGE",
    YOU_JOINED_THE_ROOM: "YOU_JOINED_THE_ROOM",
    JOINED_FOR_FIRST_TIME: "JOINED_FOR_FIRST_TIME",
    NOTIFICATION_MSG: "NOTIFICATION_MSG"
}